### ISSUE TITLE
Myst III crashes on start after update ResidualVM 

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1306] opened 2016-10-17 02:35 UTC
Windows 8.1 Pro x64
Game:  Myst III DVD Russian
ResidualVM 0.3.0git02f30c0 (Oct 16 2016 20:17:2)

C:\Program Files (x86)\ResidualVM>"C:\Program Files (x86)\ResidualVM
User picked target 'myst3-win' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
INFO: OpenGL Vendor: Intel
INFO: OpenGL Renderer: Intel(R) HD Graphics 2500
INFO: OpenGL Version: 4.0.0 - Build 10.18.10.4358
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
Initializing OpenGL Renderer
Assertion failed: idx < _size, file ./common/array.h, line 158

This application has requested the Runtime to terminate it in an unu
Please contact the application's support team for more information.

**Comment by bgK** [comment] 2016-10-17 04:39
I'm unable to reproduce this crash. Detection has changed recently. Can you try removing the game from ResidualVM and adding it again ?

I'm also curious regarding your version of the game. I didn't know there was a Russian DVD release. Is it Russian only, or is it possible to play the game in other languages ?

This build of ResidualVM has debug symbols:
http://filenurse.com/download/60ade41073fae14af13f071b51bd0d24.html
Can you run it under GDB and get a backtrace for the crash ?

**Comment by ctoroman** [comment] 2016-10-17 05:07
![image](https://cloud.githubusercontent.com/assets/22292375/19425896/9f99addc-946a-11e6-9ca2-9ecd749e8bcf.png)

**Comment by bgK** [comment] 2016-10-17 05:25
Can you please follow this tutorial for getting the backtrace, but using this GDB version:
ftp://ftp.equation.com/gdb/64/gdb.exe (And using residualvm instead of vlc, obviously).

**Comment by ctoroman** [comment] 2016-10-17 05:39
Program received signal SIGSEGV, Segmentation fault.
0x00000000005d9ca5 in Video::BinkDecoder::getAudioTrack (this=<optimized out>, index=<optimized out>) at video/bink_decoder.cpp:219
219     video/bink_decoder.cpp: No such file or directory.
(gdb) bt
#0  0x00000000005d9ca5 in Video::BinkDecoder::getAudioTrack (this=<optimized out>, index=<optimized out>) at video/bink_decoder.cpp:219
#1  0x00000000005d8b9e in Video::VideoDecoder::setAudioTrack (this=this@entry=0x23f058, index=index@entry=1) at video/video_decoder.cpp:756
#2  0x00000000005096a7 in Myst3::Movie::Movie (this=this@entry=0x23eff0, vm=<optimized out>, id=<optimized out>) at engines/myst3/movie.cpp:84
#3  0x0000000000509991 in Myst3::SimpleMovie::SimpleMovie (this=0x23eff0, vm=<optimized out>, id=<optimized out>) at engines/myst3/movie.cpp:387
#4  0x00000000004bbe29 in Myst3::Myst3Engine::playSimpleMovie (this=this@entry=0x93a7150, id=id@entry=10101, fullframe=fullframe@entry=true) at engines/myst3/myst3.cpp:1120
#5  0x00000000004bc6ba in Myst3::Myst3Engine::playMovieGoToNode (this=0x93a7150, movie=movie@entry=10101, node=node@entry=201) at engines/myst3/myst3.cpp:1550
#6  0x00000000004cc90b in Myst3::Script::moviePlayChangeNode (this=0x9469840, c=..., cmd=...) at engines/myst3/script.cpp:2229
#7  0x00000000004d3a02 in Myst3::Script::run (this=0x9469840, script=0x918ace0) at engines/myst3/script.cpp:314
#8  0x00000000004b49c7 in Myst3::Myst3Engine::runNodeBackgroundScripts (this=this@entry=0x93a7150) at engines/myst3/myst3.cpp:882
#9  0x00000000004bafce in Myst3::Myst3Engine::run (this=0x93a7150) at engines/myst3/myst3.cpp:206
#10 0x00000000004052d1 in runGame (edebuglevels=..., system=..., plugin=<optimized out>) at base/main.cpp:234
#11 scummvm_main (argc=argc@entry=1, argv=argv@entry=0x3f0aea0) at base/main.cpp:480
#12 0x0000000000402b87 in SDL_main (argc=1, argv=0x3f0aea0) at backends/platform/sdl/win32/win32-main.cpp:67
#13 0x0000000000402c0e in WinMain () at backends/platform/sdl/win32/win32-main.cpp:52
#14 0x00000000007d2b12 in main (flags=<optimized out>, cmdline=<optimized out>, inst=<optimized out>) at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18
#15 0x00000000004013ed in __tmainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#16 0x00000000004014fb in WinMainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
(gdb)

**Comment by bgK** [comment] 2016-10-17 05:58
Thanks. That was helpful. Can you please try this build and report if it works well with your version:
http://filenurse.com/download/968023a903d77ad7b228e5c0f62ba439.html

I'll push the fix to the repo later. It is in common code shared with ScummVM so I need to take extra care.

**Comment by ctoroman** [comment] 2016-10-17 06:07
The game started, but the voices are in another language, I can not understand, what, like German)))

**Comment by ctoroman** [comment] 2016-10-17 06:08
Texts in Russian

**Comment by bgK** [comment] 2016-10-17 06:19
Dutch maybe. Let's try with this build: http://filenurse.com/download/5cb8ce9a6f39703b49e32663d1b0b23b.html

**Comment by ctoroman** [comment] 2016-10-17 06:27
Now everything is all right )  Thanks )

**Comment by ctoroman** [comment] 2016-10-17 06:43
May i ask about a bug in game Riven?
I am writing here, because I can not write to the bugtracker on scummvm.org. My message was removed.

**Comment by bgK** [comment] 2016-10-17 08:42
If you want to discuss Riven, it's best to use the ScummVM forums / IRC channel. The Riven engine is not yet stable enough for us to accept bug reports.

**Comment by bgK** [comment] 2016-10-18 11:15
Fixed in d530b4f6d1bca43e0d62146ea0dd6703622a61a8

**Closed by bgK** 2016-10-18 11:15 UTC
