### ISSUE TITLE
EMI Lost Music With Newest Build?

### ISSUE THREAD

**Issue by Stingm** [residualvm/residualvm#1212] opened 2015-09-11 02:34 UTC
I want to thank you for getting full screen to finally work. The only issue now is there is no music. I can exit to main menu a few times and it will come on in the menu, but if I exit back to game it only stays on for a bit and stops. The music never comes on except for during cut scenes. Its not even on for the start of a new game. I have windows 10 I5 quad core with hd card. Thanks for any help

**Comment by Botje** [comment] 2015-09-11 08:55
Did you correctly copy the FullMonkeyMap*.imt files as described on http://wiki.residualvm.org/index.php/Datafiles ?

Can you attach the log file generated by ResidualVM? It should be in "residualvm.log" somewhere on your system.

**Comment by Stingm** [comment] 2015-09-12 02:41
I have had the fullmonkeymap files setup correctly since over a year ago. Like I said it has run fine until now it suddenly loses music. I did a search for residualvm.log and the only thing that was found was a text file in a residualvm\log directory in a hidden folder inthe system called residualvm. I'm not sure how to attach it so here is the contents: [2015-09-10 21:26:17] ResidualVM 0.3.0gitfbcf472 (Sep 10 2015 20:05:51)
[2015-09-10 21:26:17] Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 
[2015-09-10 21:26:17] --- Log opened.
[2015-09-10 21:26:47] INFO: OpenGL Vendor: Intel
[2015-09-10 21:26:47] INFO: OpenGL Renderer: Intel(R) HD Graphics
[2015-09-10 21:26:47] INFO: OpenGL Version: 2.1.0 - Build 8.15.10.2900
[2015-09-10 21:26:47] INFO: OpenGL Red bits: 8
[2015-09-10 21:26:47] INFO: OpenGL Green bits: 8
[2015-09-10 21:26:47] INFO: OpenGL Blue bits: 8
[2015-09-10 21:26:47] INFO: OpenGL Alpha bits: 8
[2015-09-10 21:26:47] INFO: OpenGL Z buffer depth bits: 24
[2015-09-10 21:26:47] INFO: OpenGL Double Buffer: 1
[2015-09-10 21:26:47] INFO: OpenGL Stencil buffer bits: 8
[2015-09-10 21:26:48] WARNING: Lua_V2::GetActiveCD: return const CD 1!
[2015-09-10 21:26:48] WARNING: Could not find sprite fx/up_arrow_small.sprb!
[2015-09-10 21:26:48] WARNING: Could not find sprite fx/down_arrow_small.sprb!
[2015-09-10 21:26:48] WARNING: Lua_V1::SetGamma, implement opcode, level: 1.000000!
[2015-09-10 21:26:48] WARNING: Could not find sprite fx/paper_smalld.sprb!
[2015-09-10 21:26:53] WARNING: Lua_V2::GetActiveCD: set to CD: 1!
[2015-09-10 21:26:53] WARNING: Lua_V2::LoadBundle: stub, name: melee!
[2015-09-10 21:26:53] WARNING: Lua_V2::GetActiveCD: set to CD: 1!
[2015-09-10 21:26:53] WARNING: Lua_V2::LoadBundle: stub, name: melee!
[2015-09-10 21:26:53] WARNING: Lua_V2::ActorStopMoving, actor: Guybrush!
[2015-09-10 21:26:53] WARNING: Lua_V2::LockBackground, filename: cdt_cred4.til!
[2015-09-10 21:26:53] WARNING: Lua_V2::LockBackground, filename: cdt_logo.til!
[2015-09-10 21:26:53] WARNING: Lua_V2::LockBackground, filename: cdt_mlogo.til!
[2015-09-10 21:26:53] WARNING: Lua_V2::LockBackground, filename: cdt_goldmonkey.til!
[2015-09-10 21:26:53] WARNING: Lua_V2::DimScreen: dim: 1.000000!
[2015-09-10 21:27:04] WARNING: Lua_V2::UndimAll: stub!
[2015-09-10 21:27:04] WARNING: Lua_V2::UnLockBackground: stub, filename: cdt_cred4.til!
[2015-09-10 21:27:04] WARNING: Lua_V2::UnLockBackground: stub, filename: cdt_logo.til!
[2015-09-10 21:27:04] WARNING: Lua_V2::UnLockBackground: stub, filename: cdt_mlogo.til!
[2015-09-10 21:27:04] WARNING: Lua_V2::UnLockBackground: stub, filename: cdt_goldmonkey.til!
[2015-09-10 21:27:04] WARNING: Lua_V2::UndimAll: stub!
[2015-09-10 21:27:04] WARNING: Lua_V2::ActorStopMoving, actor: Guybrush!
[2015-09-10 21:27:04] WARNING: Could not find bitmap wed_topdown.til!
[2015-09-10 21:27:04] WARNING: Lua_V2::LockChore, name: wear_coals, filename: fx/wed_fx.cos!
[2015-09-10 21:27:04] WARNING: Lua_V2::LockChore, name: wear_smoke, filename: fx/wed_fx.cos!
[2015-09-10 21:27:04] WARNING: Lua_V2::LockChore, name: wear_default, filename: props/fuse.cos!
[2015-09-10 21:27:04] WARNING: Lua_V2::LockChore, name: wear_default, filename: fx/fuse_spark.cos!
[2015-09-10 21:27:05] WARNING: Lua_V2::SetActorFOV: implement opcode. actor: Guybrush, param: 120.000000!
[2015-09-10 21:27:05] WARNING: Lua_V2::DimScreen: dim: 1.000000!
[2015-09-10 21:27:11] WARNING: Could not find sprite fx/paper_smalld.sprb!
[2015-09-10 21:27:17] WARNING: Lua_V2::GetActiveCD: set to CD: 1!
[2015-09-10 21:27:17] WARNING: Lua_V2::LoadBundle: stub, name: melee!
[2015-09-10 21:27:25] WARNING: Could not find sprite fx/paper_smalld.sprb!
[2015-09-10 21:27:28] WARNING: Could not find sprite fx/paper_smalld.sprb!
[2015-09-10 21:27:31] WARNING: Lua_V2::SetActorFOV: implement opcode. actor: Guybrush, param: 120.000000!
[2015-09-10 21:27:31] WARNING: Lua_V2::UnlockChore, name: wear_coals, filename: fx/wed_fx.cos!
[2015-09-10 21:27:31] WARNING: Lua_V2::UnlockChore, name: wear_smoke, filename: fx/wed_fx.cos!
[2015-09-10 21:27:31] WARNING: Lua_V2::UnlockChore, name: wear_default, filename: props/fuse.cos!
[2015-09-10 21:27:31] WARNING: Lua_V2::UnlockChore, name: wear_default, filename: fx/fuse_spark.cos!
[2015-09-10 21:27:31] --- Log closed successfully.
Hope this is the file and helps

**Comment by chkr-private** [comment] 2015-09-15 23:20
This regression is caused by the latest sync with scummvm in commit 5c7fd277067290be128862d1e166052320f104aa.

I created a pull request to get it fixed in the scummvm repository first: https://github.com/scummvm/scummvm/pull/615. You can test the bug fix by just applying https://github.com/chkr-private/scummvm/commit/d16d87e2c860fb36888f0972ccb28bdf25d2684d to the residualvm source.

**Comment by chkr-private** [comment] 2015-09-16 18:07
Fixed by commit baab5c4223cd58731f944b0a0319a26027eb4f9e. @aquadran, @clone2727: Thanks for the quick help.

**Closed by chkr-private** 2015-09-16 18:07 UTC
