### ISSUE TITLE
TLJ: HD Tobias Grensret Faces away from book when idle, also Duck Air Hissing noise

### ISSUE THREAD

**Issue by LiveFreeDead** [residualvm/residualvm#1586] opened 2019-12-07 10:01 UTC
During all the chapters Tobias is reading his scriptures he was standing facing away from the book with his hands behind his back, when you talk with him the animation jumps back to him reading and then he turns back to that position VERY rapidly and talks as expected, once he's done talking he stays in that position again. I have completed the whole game with the HD modifications applied, no crashes or impasse occurred.

The only other glitch was when I blew up the rubber ducky I put it on the clamp and lowered it down to retrieve the key from train track, but then I went on the train and back to the old theater, the air hissing noise kept playing, it continued until I got sick of it after 5-6 minutes, then I quit and ran the game again, the air hissing was gone.

**Comment by bgK** [comment] 2019-12-08 14:08
Hi,

Thanks for your report. Do you have some indications how to make these issues happen? I've tried replaying the shift to Marcuria, but Tobias is facing in the appropriate direction. I've also been unable to reproduce the issue with the duck deflating sound.

Perhaps you could attach a save file for when Tobias is facing in the incorrect direction?

**Comment by LiveFreeDead** [comment] 2019-12-09 01:14
If you blow up the duck with the bandaid on, attach the rope to the clamp, Look at duck and remove bandaid, then use duck on clamp/rope, use the item to retrieve the key near track and then skip voice and go on to train the hissing noise continues for quite a while longer, I quit the first time and reloaded fine without the sound. 2nd time I'm gonna leave it and see if it follows me to Marcuria. Will be back once I play through to there as I saved over my earlier chapter saves so will see if the glitch occurs again on me.

**Comment by LiveFreeDead** [comment] 2019-12-09 01:36
Yes the Air hiss follows me between worlds and I don't even have the duck in my inventory anymore.

The Wrong direction glitch didn't occur this time, so it must be temperamental. Sorry I couldn't be more help.

**Comment by bgK** [comment] 2019-12-11 19:58
Thanks! The sound issue is now fixed. I'll try investigating Tobias' direction at some later point.

**Comment by webfischi** [comment] 2020-01-08 15:33
I can confirm the direction issue, I think I talked to him, then left the building and reentered.

**Closed** 2020-10-15 23:13 UTC
Labels: Stark
