### ISSUE TITLE
GRIM: Buggy character in the Blue Casket when using the Software Renderer

### ISSUE THREAD

**Issue by marespiaut** [residualvm/residualvm#1251] opened 2016-06-06 23:38 UTC
Hello,

[In this savegame](https://bfs.u-bordeaux.fr/telecharge.php?choix=files/66a0de74937aef383e531d089dc6cb96/grim04.gsv), the character at the right of the screen is buggy (it disapear) when using the software renderer instead of the OpenGL one.

I'm running revision 0bda7cd00bb59992fdb992f2d101591aafd40603 on ArchLinux x86_64.

**Comment by vpelletier** [comment] 2016-07-17 08:37
The same issue happens in the casino set (cn). The reason why it behaves differently with tinygl than with opengl is that game scripts check if 3D acceleration is enabled. When disabled, it tells the engine to render some non-moving actors to a buffer, to be then blit over the image instead of rendering them each time.
For some reason, this is broken in residualvm at the moment.

**Comment by vpelletier** [comment] 2016-11-06 09:48
This bug is likely a duplicate of #1042 .

**Comment by vpelletier** [comment] 2017-05-02 09:52
Fixed by #1335 .

**Closed by vpelletier** 2017-05-02 09:52 UTC
Labels: Graphics, GRIM, TinyGL
