### ISSUE TITLE
[The Longest Journey] HD Mod Fullscreen problems

### ISSUE THREAD

**Issue by GrimChaos** [residualvm/residualvm#1543] opened 2019-05-19 23:54 UTC
In windowed mode it pulls in the HD files from the mods folder but switching to full-screen it does not.  Even switching (alt-enter) to full-screen from windowed doesn't work.

**Comment by bgK** [comment] 2019-05-30 10:08
It's possible the root cause for this issue was the same as #1547. Could you please try this build of ResidualVM and see if the issue is resolved:
https://ufile.io/o7nchg9w

**Comment by bgK** [comment] 2019-11-07 11:00
Closing due to lack of answer from OP. Please re-open if you encounter that issue.

**Closed by bgK** 2019-11-07 11:00 UTC
Labels: Stark
