### ISSUE TITLE
Duplicate key input since latest scummvm sync

### ISSUE THREAD

**Issue by vpelletier** [residualvm/residualvm#1332] opened 2017-04-19 15:02 UTC
Since 19bcd1f3bc1383eac50ec59307d4c9348a20e150 (verified by bisecting), pressing a keyboard key once triggers two actions.

Visible at least in GRIM in:
- dialogs between characters, where up/down arrows skip every other line
- ^G dialog to jump to a scene: it contains a "g" upon entry, and any key typed is duplicated. Trying to go to "ca" gives: "gccaa".

/cc @aquadran 
[EDIT] There are two very different types of "dialog" here...

**Comment by vpelletier** [comment] 2017-04-20 13:04
This is also visible in other engines/games:
- in MYST3 when typing savefile name.
- in EMI when in the "load" menu (entering it by pressing <enter> triggers the "are you sure you want to load" dialog), though navigating by cursor keys in the main menu is fine
- in STARK in the "save" dialog in option menu (like for grim "go" dialog, this is residualvm UI)

**Comment by bgK** [comment] 2017-04-20 13:22
I can't reproduce that (Linux + SDL2). What platform / SDL version are you using?

**Comment by vpelletier** [comment] 2017-04-20 13:28
Debian sid, amd64

```
$ ldd residualvm | grep -i sdl
        libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f7cd3ed4000)
$ dpkg -S /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
libsdl2-2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
```

Package installed as of 2.0.5+dfsg1-2 .

Diff-ing config.log and config.h before/after mentioned commit find no change, *but* it then links against libSDL-1.2, which I also have available on my system (here at e72761a05e49ba711bea2183228d42af5539a524):

```
$ ldd residualvm | grep -i sdl
        libSDL-1.2.so.0 => /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0 (0x00007fc6a2962000)
```

Funny.

**Comment by vpelletier** [comment] 2017-04-20 13:40
Aha, not a weird side-effect actually, but as in the patch: configure moves from `sdl-config` to `sdl2-config`. Need more investigations...

**Comment by vpelletier** [comment] 2017-04-20 15:21
So, the events come twice as KEYDOWN, one with `repeat=0`, the other with `repeat=1`:
```
WARNING: type=768 timestamp=3692 state=1 repeat=0!
WARNING: type=768 timestamp=3693 state=1 repeat=1!
WARNING: type=768 timestamp=5265 state=1 repeat=0!
WARNING: type=768 timestamp=5266 state=1 repeat=1!
```
I have no idea why I would ver repeats so quickly one after the other.

**Comment by bgK** [comment] 2017-04-20 15:42
Do you get a repeat event for a short keypress in kernel / X11 event debugging tools as well? (evtest / xev)

**Comment by vpelletier** [comment] 2017-04-20 15:48
And that's not all there is :( .

While making `SdlEventSource::pollEvent` continue on repeat does fix dialogue line selection in GRIM and m, and while it fixes the initial "g", pressing any alpha key appends two chars. Backspace removes one char, so it's kind of functional...

This also fixes EMI menu selection.

In MYST3, savegame name input still has the issue.

**Comment by vpelletier** [comment] 2017-04-20 15:57
I do have an auto-repeat (and on a rather short delay, kde shows a 250ms threshold and 25 repeats/s after, which is my usual setting), but even extremely short alnum presses cause dupes in GRIM "go" dialog. A bit long press on xev, likely not far from auto-repeat yields only one press and one release event:
```
KeyPress event, serial 40, synthetic NO, window 0xa200001,
    root 0x1e3, subw 0x0, time 269929405, (1022,598), root:(2944,619),
    state 0x0, keycode 25 (keysym 0x7a, z), same_screen YES,
    XLookupString gives 1 bytes: (7a) "z"
    XmbLookupString gives 1 bytes: (7a) "z"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0xa200001,
    root 0x1e3, subw 0x0, time 269929517, (1022,598), root:(2944,619),
    state 0x0, keycode 25 (keysym 0x7a, z), same_screen YES,
    XLookupString gives 1 bytes: (7a) "z"
    XFilterEvent returns: False
```

**Comment by bgK** [comment] 2017-04-20 18:05
This may be relevant: https://hg.libsdl.org/SDL/rev/b48d8a98e261
Do you have an IME running on your system?

**Comment by vpelletier** [comment] 2017-04-20 22:58
Nice catch, I do have fcitx configured. And running residualvm with `XMODIFIERS=@im=none` indeed fixes the issue.

**Comment by bgK** [comment] 2017-04-21 16:24
Good ... I guess.

I'm closing this since it is not a ResidualVM bug and it has already been fixed in SDL.

**Closed by bgK** 2017-04-21 16:24 UTC
