### ISSUE TITLE
Can't compile Android version

### ISSUE THREAD

**Issue by Smashman4** [residualvm/residualvm#1673] opened 2020-08-17 01:19 UTC
Not sure if I should make an issue about this but let's do it. Thought I would take another try at compiling the android version again. Now I'm getting the issue that it can't find the C++ compiler. I tried on both Mac and Windows and I get the same result. I set both SDK and NDK locations correctly. Any fix for this?

**Comment by aquadran** [comment] 2020-08-17 06:14
Android version compiling fine: https://travis-ci.org/github/residualvm/residualvm/jobs/718444661

**Comment by Smashman4** [comment] 2020-08-17 13:31
Then why do I get this error? 
<img width="293" alt="Screen Shot 2020-08-17 at 9 31 12 AM" src="https://user-images.githubusercontent.com/29053081/90401799-7909da00-e06c-11ea-9e15-9eb9f7b1fc30.png">

**Comment by Botje** [comment] 2020-08-17 14:39
See the `.travis/android-set-environment` and `.travis/androis-build` scripts.

**Comment by Smashman4** [comment] 2020-08-17 15:36
ok. got the apk made now, but it's unsigned.

**Comment by Botje** [comment] 2020-08-17 17:01
And what error message do you get? Did you compile for the right architecture?

**Comment by Smashman4** [comment] 2020-08-17 17:06
when installing over adb, I get this message: [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

and I'm installing the arm64-v8a architecture on an android 8.1 64bit device.

**Comment by Botje** [comment] 2020-08-17 17:17
According to [this link](https://github.com/iBotPeaches/Apktool/issues/1626) it might be caused by extractnativelibs being false in the manifest. I just disabled it because android studio told me to. Try flipping it to true.

**Comment by Smashman4** [comment] 2020-08-17 17:38
It installed without errors, but now when I launch it the first time, it will say I don't have a micro sd inserted. After tapping quit and relaunching, it just keeps closing out.

**Comment by aquadran** [comment] 2020-10-03 17:06
closing as no longer build issue

**Closed by aquadran** 2020-10-03 17:06 UTC
Labels: Build issue
