### ISSUE TITLE
Full screen multiple monitors not handled correctly in Linux 

### ISSUE THREAD

**Issue by jamie-marchant** [residualvm/residualvm#1579] opened 2019-10-21 00:27 UTC
I am running XFEC in Fedora 29 and when I put residual VM fullscreen(even with no game running), it stretches across both monitors rather than using my primary monitor. If I enable "cloneing" or disable one of my screen it works properly. I am not sure if this a limitation of "SDL" as I do see this in other games too but they normally work around the problem by clone.

**Comment by bgK** [comment] 2019-11-01 12:37
Hi,

I've been unable to reproduce the issue you describe (neither in Xorg or Wayland). However I did find and fix an issue related to the case where the screens have different resolutions. Would you mind testing the newest master version to see if your issue is still there?

As a workaround, you can set `fullscreen_res=1920x1080` in your `residualvm.ini` configuration file to force a fullscreen resolution.

**Comment by bgK** [comment] 2020-01-05 15:21
Closing due to lack of answer. Please re-open if needed.

**Closed by bgK** 2020-01-05 15:21 UTC

**Comment by jamie-marchant** [comment] 2020-01-05 19:49
Oh, I missed the email notification or forgot about this. Can reproduce on "master" and strangely your workaround still stretches the image across the screen but it's a bit more in the centre. My two monitors are NOT the same size or ratio, one of them is a 5:4 1280x1024 display I picked up at the thrift store and the other is a modern HD monitor I got years ago if this helps. 

I only have 1 game that I can use with RisdualVM and it's Monkey Island 4, it's 4:3 and using a lower res 4:3 res(like 1024x768) works around this but leaves my monitors cloned when I exit but that's better then what I had before and is a useable workaround.
