### ISSUE TITLE
EMI: PC Certain parts of screen are black?

### ISSUE THREAD

**Issue by Stingm** [residualvm/residualvm#1345] opened 2017-05-21 11:04 UTC
For example on the screen with the catapault  and your mansion the catapault, the cannballs and the targeting cactus are black. Everything else is fine. I tried all graphic display modes and only software non full screen shows the scene correctly. I did notice that timmy the monkey was black in the cutscene before as well but as it loaded the next scene the black went away momentarily. What cold be causing this issue and can it be fixed?

**Comment by Botje** [comment] 2017-05-22 07:13
We'll need a bit more information than that:

1. What operating system and graphics hardware are you running?
2. What does the ResidualVM log say?
3. Can you try with the Grim Fandango demo? (http://www.residualvm.org/downloads/#extras)
4. Do you see the same issue with any other OpenGL games? (free ones like Sauerbraten, Warsow, ...)

**Comment by Stingm** [comment] 2017-05-22 17:37
I have a windows 10 laptop with hd card. Where is the log? I can post if you tell me where it is?

**Comment by Botje** [comment] 2017-05-23 04:30
"hd card" is really not specific enough. Look at the device manager in your control panel. Which graphics cards do you have?
The log is at `C:\Users\Dries\AppData\Roaming\ResidualVM\Logs` for me, but that's on windows 7 and it was a while ago.
I also forgot to ask which version of ResidualVM you are running.

What about the other questions?

**Comment by Stingm** [comment] 2017-05-24 02:22
I'm running the latest version from daily builds. The device manager say interR hd graphics.  Here is the log file: 
[2017-05-21 05:58:21] ResidualVM 0.3.0git2490cb98 (May 15 2017 22:25:50)
[2017-05-21 05:58:21] Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 
[2017-05-21 05:58:21] --- Log opened.
[2017-05-21 05:58:50] --- Log closed successfully.

**Comment by Botje** [comment] 2017-05-24 07:25
All this log file shows is that you started ResidualVm and closed it 29 seconds later. Did you enter the game in that session?

Finally, please report your results with the Grim demo and other OpenGL games.

**Comment by Stingm** [comment] 2017-05-27 01:02
Okay sorry I have been busy with work. I ran the game again and let it go through the cutscene after shooting the ship with the cannon. Timmy, Guybrushes feet, catapault, cannon balls, and targeting cactus were black. Heres the log: 


[residualvm.txt](https://github.com/residualvm/residualvm/files/1033207/residualvm.txt)

**Comment by Botje** [comment] 2017-05-29 07:17
Doesn't look like a data issue, at least.

I'm guessing this is probably due to your Intel drivers not supporting a recent-ish version of OpenGL (because Intel HD graphics and Windows 10 do not mix).
Is the result the same if you turn off OpenGL Shaders? You can find those under the graphics tab in the settings for the game entry.

**Comment by Stingm** [comment] 2017-05-29 16:59
As stated in first post I tried all display options and it only works right in software non full screen. Even software full don't work. Why would non full work but not full screen in software?

**Comment by Botje** [comment] 2017-05-29 19:44
I can now reproduce this on my windows 7 installation with the latest daily build. I'll try on Linux tomorrow, as that's where I usually develop.

**Comment by Botje** [comment] 2017-05-30 05:42
Cannot reproduce on Linux, and now I cannot reproduce it on Windows OpenGL either ...

**Comment by Stingm** [comment] 2017-06-22 04:40
It is definitely a residualvm issue as the game runs fine without it. I even got the launcher from International house of mojo and it works fine with no black areas. I hope you can fix this soon.

**Comment by Botje** [comment] 2017-06-22 06:09
Can't fix it if I can't reproduce it... Can you provide a save file with
the issue? If it travels with the save file I at least have a starting
point for debugging.

**Comment by Stingm** [comment] 2017-06-22 16:54
If I get a chance I will post it. I just don't know when it will happen with work and all.

**Comment by Stingm** [comment] 2017-11-24 17:12
Okay I have fixed this issue some how. I reinstalled the full game and used the newest version of residualvm. I had to change to opengl with shaders as that is the only way it works. All black areas are gone except for guybrushes shoes. Were they always black?

**Comment by smithrobs** [comment] 2018-01-13 00:42
I can reproduce this with OpenGL (**no** shaders) and in fullscreen. It is fine for me in OpenGL & shaders as well as software.

`0.4.0git34-g87218254 (Jan 8 2018 10:35:31)`

![1](https://user-images.githubusercontent.com/245836/34900733-6fd0a608-f7d0-11e7-9e17-027f10b788ea.png)
![2](https://user-images.githubusercontent.com/245836/34900734-6fda63d2-f7d0-11e7-9d96-841b24da9c6a.png)

**Comment by Stingm** [comment] 2018-01-26 04:20
I'm just glad it works again. Thank you guys for a great program. So what is it about no shaders that makes certain things black?

**Comment by Botje** [comment] 2020-05-22 13:51
Now that I see the image again; this might be a dup of #1263 which was solved in #1478. Please reopen if this issue is still there.

**Closed by Botje** 2020-05-22 13:51 UTC
Labels: EMI, Graphics
